apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: node-web-app
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: node-web-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60

